### ISSUE TITLE
Cannot build agent

### ISSUE THREAD

**Issue by stsypanov** [apangin/vmtrace#1]
I've checked out the project and then moved into `/src`

Then I run command from README and get this:
```
s.tsypanov@UAIEV8529NBL:~/IdeaProjects/vmtrace/src$ gcc -O2 -fPIC -shared -Wl,-soname,libvmtrace.so -olibvmtrace.so vmtrace.c
vmtrace.c:17:10: fatal error: jvmti.h: No such file or directory
 #include <jvmti.h>
          ^~~~~~~~~
compilation terminated.
s.tsypanov@UAIEV8529NBL:~/IdeaProjects/vmtrace/src$ 
```
I feel I'm missing some config, so is it possible to specify it in README?

**Comment by apangin** [comment]
This project is obsoleted by [odnoklassniki/jvmti-tools](https://github.com/odnoklassniki/jvmti-tools), which includes vmtrace as one of the examples.

There is also [README](https://github.com/odnoklassniki/jvmti-tools#vmtrace) with a short instruction how to build and run the tools.

Please submit further issues in jvmti-tools project.
I'll archive this one.
